### ISSUE TITLE
Develop a light-weight front-end for the getting started app

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/sample-getting-started#1]
The UI should cleanly expose a landing page which links/showcases the technologies the app implements and exposes (MP health, metrics, & config).

Priority: Done by Think (March 19th)

**Requirements:**
- Display system properties #2
- Showcase microprofile config
- Showcase microprofile metrics #3 
- Showcase microprofile health #4

**Comment by kinueng** [comment]
**Requirements:**
- Display system properties
- Showcase microprofile config
- Showcase microprofile metrics
- Showcase microprofile health
