### ISSUE TITLE
Trademark mentions on UI

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/sample-getting-started#15]
There are two mentions of "MicroProfile^TM" on the sample UI. If we *have* to include trademark attributions here, we need to do them correctly. So only the first mention should include the mark and I think it should be "Eclipse MicroProfile^TM" (ie include Eclipse in the first mention with the trademark). @kwsutter will know what the minimum requirement is but also see link [4] in this issue: https://github.com/microprofile/microprofile-site-config/issues/76.

(Also, there's a weird line break in the 'sweet MicroProfile' paragraph.)

**Comment by kwsutter** [comment]
@lauracowen is correct.  Nice catch!  At a minimum, the first mention of MicroProfile should be the full name with the TM -- Eclipse MicroProfile^TM.  This would be the first mention in a blog, or the UI, or guide write-up, etc.  I'm guessing we missed these in the Guides.  I'll take a quick look and see if an issue needs to be raised.

**Comment by kevinwlau** [comment]
Fixed by #22
