### ISSUE TITLE
The run commands are weird...(and inconsistent with Liberty Maven plugin)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/sample-getting-started#16]
The sample commands are a bit odd and inconsistent with our use of the Liberty Maven plugin elsewhere.

The command `mvn clean install` should only build the app and install it (and run the tests, I think) but not run it.

## Current behaviour:

According to the [instructions in the readme](https://github.com/OpenLiberty/sample-getting-started/blob/master/README.md), to run the sample you run `mvn clean install`. This does not run the tests and then starts the server in the background. Even though this makes the command shorter, it is inconsistent with our other guides and I think is confusing.

## Suggested new behaviour:

Make the sample app start with the command `mvn clean install liberty:run-server` and run the tests (we could document the option to use `mvn clean install -DskipTests liberty:run-server` in the readme though don't know it's necessary?).

That way, it's consistent with the guides etc and shows we care about tests. Also, by running in the foreground, it's easy to stop the server without having to read the readme or something (ie CTRL+C). And the URL to visit is displayed in the console too. (as discussed with @gcharters )

**Comment by cbridgha** [comment]
should be all set
