### ISSUE TITLE
Getting started sample Metrics problem

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/sample-getting-started#21]
In the sample UI I see the message "Internal Server Error" when I expand the Metrics section.

From the server output, I see:

[INFO] [AUDIT   ] CWWKF0011I: The server sampleAppServer is ready to run a smarter planet.
[INFO] [WARNING ] Interceptor for {https://10.5.35.42:9443/metrics/}WebClient has thrown exception, unwinding now
[INFO] Could not send Message.
[INFO] [WARNING ] Application {http://metrics.sample.openliberty.io/}MetricsOverHTTPResource has thrown exception, unwinding now
[INFO] java.io.IOException: IOException invoking https://10.5.35.42:9443/metrics/: HTTPS hostname wrong:  should be <10.5.35.42>

Accepting the self-signed cert in the browser does not fix the problem.

**Comment by cbridgha** [comment]
@mbroz2 Have you seen this issue? - I haven't

**Comment by mbroz2** [comment]
I have not (neither has anyone on the team), been in talks with Graham regarding seeing if he can reproduce it.
