### ISSUE TITLE
Create release tags

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/sample-getting-started#67]
We want to use this sample app as the default application image in the sample custom resources of Open/WebSphere Liberty Operators. At the moment, this application image doesn't have any tags. It has the default `latest` tag. In the operator, we have to reference the image using a digest (sha256) value. Some registries clean up images if it's not associated with any tags. Not sure if icr.io does that. But in any case, it'll be good to create releases for sample applications.

@mbroz2 could you please help with this? Thanks.

**Comment by mbroz2** [comment]
Confirmed that, by default, icr.io [does not automatically delete untagged images](https://cloud.ibm.com/docs/Registry?topic=Registry-registry_retention).  A retention policy would need to be put in place that would delete the untagged images in teh namespace.  Therefore no action is necessary and closing this issue.

**Comment by leochr** [comment]
@mbroz2 thanks for confirming that the sample app images are not cleaned up by icr.io. Please let me know if that changes in the future. 

FYI, this is the image we are using within the Liberty operators at the moment. We'll update it on May 24th - just before the code freeze to pull in the latest image. 
`icr.io/appcafe/open-liberty/samples/getting-started@sha256:5d3afaf6f5b4762213ab6fdabb2f1d8d8b374646702ef50a46f784795147fac3`
