### ISSUE TITLE
Add multi-arch support

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/sample-getting-started#79]
Add support for P and Z Linux platforms

**Comment by leochr** [comment]
This app is used as the sample in various artifacts, including in Liberty Operators. Multi-arch support for Operator is planned for 2Q23 (release date April 25). We need the sample app to support P and Z as well.

@mbroz2 could this support be added? Please let me know if you need any help

**Comment by leochr** [comment]
@mbroz2 @crpotter Please share any updates/plans to add support for this. Thank you.

We can build multi-arch images for P and Z (manually for now) and are looking for a sample app, with multi-arch support, to test with.

**Comment by mingcyu** [comment]
Corresponding CD/CC Squad work item => https://github.ibm.com/WAS-CD-Area/WAS-CD-Area/issues/864

**Comment by leochr** [comment]
@NottyCode The getting-started sample application is referenced in Liberty Operator's sample custom resource (CR). 

```
kind: WebSphereLibertyApplication
apiVersion: liberty.websphere.ibm.com/v1
...
spec:
  applicationImage: >-
    icr.io/appcafe/open-liberty/samples/getting-started@sha256:baf8bc7b...
    ...
```

If P & Z support is not added for this sample app in time for the April releases of WLO, one option is to reference the Liberty runtime image (i.e. `icr.io/appcafe/websphere-liberty@sha256:40d78f35...`) in the sample CR, which will just display the Liberty welcome page. Once this app supports multi-arch, we can reference it again in a subsequent Operator release. I am not aware of any other Liberty sample app that supports multi-arch. We just wanted to run it by you to see if you have any concerns about this option. Thank you.
